title: WriteUps from zeno-dot
description: Разборы комнат TryHackMe и других CTF-машин
baseurl: "/WriteUp-from-zeno-dot"
theme: jekyll-theme-slate

defaults:
  - scope:
      path: ""
    values:
      layout: default
